force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Medical Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <description>Doctor</description>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Medical Facility where the Medical Appointment will take place</description>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Medical_Appointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Patient</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Patient_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <description>Healthcare facility, such as a hospital or clinic.</description>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Represents an individual person, such as a doctor or patient.</description>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Person&apos;s name</description>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Person&apos;s last name.</description>
    <label>Last Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Medical_Facility__c.field-meta.xml
<CustomField>
    <fullName>Medical_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Medical Facility</label>
    <referenceTo>Medical_Facility__c</referenceTo>
    <relationshipLabel>People</relationshipLabel>
    <relationshipName>People</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/PESEL__c.field-meta.xml
<CustomField>
    <fullName>PESEL__c</fullName>
    <description>Person&apos;s PESEL number.</description>
    <label>PESEL</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Person__c/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

force-app/main/default/classes/MedicalAppointmentNameTriggerTest.cls
@isTest
public class MedicalAppointmentNameTriggerTest {
    @isTest
    static void testBulkTrigger() {
        Medical_Facility__c facility = new Medical_Facility__c(Name = 'City Hospital');
        insert facility;

        Person__c doctor = new Person__c(
            Last_Name__c = 'Smith',
            First_Name__c = 'John',
            PESEL__c = '12345678',
            Medical_Facility__c = facility.Id
        );
        insert doctor;

        List<Person__c> patients = new List<Person__c>();
        for (Integer i = 1; i <= 10; i++) {
            patients.add(new Person__c(
                Last_Name__c = 'Doe' + i,
                First_Name__c = 'Jane' + i,
                PESEL__c = '12345678' + i
            ));
        }
        insert patients;

        List<Medical_Appointment__c> appointments = new List<Medical_Appointment__c>();

        for (Person__c patient : patients) {
            appointments.add(new Medical_Appointment__c(
                Patient__c = patient.Id,
                Doctor__c = doctor.Id,
                Appointment_Date__c = DateTime.newInstance(2024, 12, 28, 10, 30, 0)
            ));
        }
        insert appointments;

        List<Medical_Appointment__c> savedAppointments = [
            SELECT Name
            FROM Medical_Appointment__c
            WHERE Id IN :appointments
        ];

        for (Integer i = 0; i < savedAppointments.size(); i++) {
            String expectedName = 'City Hospital-Smith-Doe' + (i + 1) + '-28-12-2024';
            System.assertEquals(expectedName, savedAppointments[i].Name, 'Nazwa rekordu nie jest zgodna dla indeksu: ' + i);
        }
    }
    @isTest
    static void testIncompleteTrigger() {
        Person__c doctor = new Person__c(
            Last_Name__c = 'Smith',
            First_Name__c = 'John',
            PESEL__c = '12345678'
        );
        insert doctor;

        Person__c patient = new Person__c(
            Last_Name__c = 'Doe',
            First_Name__c = 'Jane',
            PESEL__c = '12345678'
        );
        insert patient;

		Medical_Appointment__c appointment = new Medical_Appointment__c(
            Patient__c = patient.Id,
            Doctor__c = doctor.Id,
        	Appointment_Date__c = DateTime.newInstance(2024, 12, 28, 10, 30, 0)
        );
        insert appointment;

        appointment = [SELECT Name FROM Medical_Appointment__c WHERE Id = :appointment.Id];
        
        System.assertEquals('Incomplete Information', appointment.Name);
    }
}