force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Medical Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GetAppointmentDateBot.cls
public with sharing class GetAppointmentDateBot {
    public class AppointmentOutput {
        @InvocableVariable(required=true)
        public DateTime AppointmentDate;
    }
    
    public class AppointmentInput {
        @InvocableVariable(required=true)
        public String AppointmentId;
    }
    
    @InvocableMethod(label='Check Appointment Date')
    public static List<AppointmentOutput> GetAppointmentDate(List<AppointmentInput> appointmentInputs){
        Set<String> appointmentIds = new Set<String>();
        
        for(AppointmentInput appInp : appointmentInputs){
            appointmentIds.add(appInp.AppointmentId);
        }
        
        List<Medical_Appointment__c> appointments = [
            SELECT Name, Appointment_Date__c 
            FROM Medical_Appointment__c 
            WHERE Name IN :appointmentIds
        ];
        
        Map<String, DateTime> appointmentDateMap = new Map<String, DateTime>();

        for(Medical_Appointment__c app : appointments){
            appointmentDateMap.put(String.valueOf(app.Name), app.Appointment_Date__c);
        }

        List<AppointmentOutput> appointmentOutputs = new List<AppointmentOutput>();

        for(AppointmentInput appInp : appointmentInputs){
            AppointmentOutput appOut = new AppointmentOutput();
            if (appointmentDateMap.containsKey(appInp.AppointmentId)){
                appOut.AppointmentDate = appointmentDateMap.get(appInp.AppointmentId);
            } else {
                appOut.AppointmentDate = null;
            }
            appointmentOutputs.add(appOut);
        }
        return appointmentOutputs;
    }
}