force-app/main/default/objects/Medical_Appointment__c/Medical_Appointment__c.object-meta.xml
<CustomObject>
    <label>Medical Appointment</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Medical Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medical Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Date__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date__c</fullName>
    <label>Appointment Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Appointment_Name__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Name__c</fullName>
    <description>Custom_Name for AppointmentNameTrigger</description>
    <label>Appointment Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <description>Doctor</description>
    <label>Doctor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Appointments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Medical_Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Patient</description>
    <label>Patient</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Person__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Patient</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Medical Appointments</relationshipLabel>
    <relationshipName>Patient_Appointments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Represents an individual person, such as a doctor or patient.</description>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The person&apos;s email address</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Person&apos;s name</description>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Person&apos;s last name.</description>
    <label>Last Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Person__c/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <label>Patient</label>
</RecordType>

force-app/main/default/classes/EmailManager.cls
public class EmailManager {
    public static void sendAppointmentEmail(List<Medical_Appointment__c> appointments, List<Person__c> persons) {
        EmailTemplate template = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'AppointmentUpdateMail' LIMIT 1];
        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();        

        for(Integer i = 0; i < appointments.size(); i++) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            Medical_Appointment__c appt = appointments[i];
            Person__c patient = persons[i];
            Person__c doctor = persons[i + 1];

            String htmlBody = template.HtmlValue;
            htmlBody = htmlBody
                .replace('{!Medical_Appointment__c.Appointment_Name__c}', appt.Appointment_Name__c)
                .replace('{!Patient__c.First_Name__c}', patient.First_Name__c)
                .replace('{!Patient__c.Last_Name__c}', patient.Last_Name__c)
                .replace('{!Doctor__c.First_Name__c}', doctor.First_Name__c)
                .replace('{!Doctor__c.Last_Name__c}', doctor.Last_Name__c)
                .replace('{!Medical_Appointment__c.Appointment_Date__c}', String.valueOf(appt.Appointment_Date__c));

            String[] toAddresses = new String[] {patient.Email__c};
            mail.setToAddresses(toAddresses);
            mail.setSubject('Aktualizacja wizyty lekarskiej');
            mail.setHtmlBody(htmlBody);
            emailsToSend.add(mail);
        }
        
        if(!emailsToSend.isEmpty()) {
            Messaging.SendEmailResult[] results = Messaging.sendEmail(emailsToSend);
            inspectResults(results);
        }
    }
    
    private static void inspectResults(Messaging.SendEmailResult[] results) {
        for (Messaging.SendEmailResult res : results) {
            if (res.isSuccess()) {
                System.debug('Email sent successfully');
            } else {
                System.debug('The following errors occurred: ' + res.getErrors());
                
                Messaging.SingleEmailMessage errorMail = new Messaging.SingleEmailMessage();
                String[] adminEmails = new String[] {'245775@edu.p.lodz.pl'}; 
                
                errorMail.setToAddresses(adminEmails);
                errorMail.setSubject('Błąd podczas wysyłania maila - Medical Appointment Update');
                errorMail.setPlainTextBody('Wystąpił błąd podczas wysyłania maila:\n' + String.join(res.getErrors(), '\n'));
                
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { errorMail });
            }
        }
    }
}