force-app/main/default/objects/Medical_Facility__c/Medical_Facility__c.object-meta.xml
<CustomObject>
    <description>Healthcare facility, such as a hospital or clinic.</description>
    <label>Medical Facility</label>
    <nameField>
        <label>Medical Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medical Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medical_Facility__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <externalId>true</externalId>
    <label>Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Opening_Hours__c.field-meta.xml
<CustomField>
    <fullName>Opening_Hours__c</fullName>
    <label>Opening Hours</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Medical_Facility__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <description>Contact number of the medical facility.</description>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/MedicalFacilitiesSyncTest.cls
@isTest
private class MedicalFacilitiesSyncTest {
    @isTest static void testUpsert() {
        Test.setMock(HttpCalloutMock.class, new MedicalFacilitiesHttpMock());
        Test.startTest();
        MedicalFacilitiesSync sync = new MedicalFacilitiesSync();
        System.enqueueJob(sync);
        Test.stopTest();

        List<Medical_Facility__c> facilities = [
            SELECT Name, Phone_Number__c, Address__Street__s, Address__PostalCode__s, Address__City__s, Opening_Hours__c, Id__c, Email__c
            FROM Medical_Facility__c
        ];
        System.assertEquals(1, facilities.size());
        System.assertEquals('Jeż Medyczny', facilities[0].Name);
        System.assertEquals('+48 123 456 780', facilities[0].Phone_Number__c);
        System.assertEquals('Puławska 45', facilities[0].Address__Street__s);
        System.assertEquals('02-508', facilities[0].Address__PostalCode__s);
        System.assertEquals('Warszawa', facilities[0].Address__City__s);
        System.assertEquals('Poniedziałek: "10:00 - 16:00"\nWtorek: "10:00 - 16:00"\nŚroda: "10:00 - 19:00"\nCzwartek: "9:00 - 17:00"\nPiątek: "8:00 - 16:00"\nSobota: "9:00 - 19:00"\nNiedziela: "9:00 - 19:00"', facilities[0].Opening_Hours__c);
        System.assertEquals('AB123456', facilities[0].Id__c);
        System.assertEquals('kontakt0@placowka.com', facilities[0].Email__c);
    }
}