force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Represents an individual person, such as a doctor or patient.</description>
    <label>Person</label>
    <nameField>
        <label>Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/DoctorId__c.field-meta.xml
<CustomField>
    <fullName>DoctorId__c</fullName>
    <externalId>true</externalId>
    <label>DoctorId</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Person&apos;s name</description>
    <label>First Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Person&apos;s last name.</description>
    <label>Last Name</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Personal_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Personal_ID_Number__c</fullName>
    <description>An individual&apos;s personal identification number (PESEL).</description>
    <label>Personal ID Number</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Person__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>Working schedule for Doctor</description>
    <label>Schedule</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Person__c/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/classes/DoctorScheduleSyncTest.cls
@isTest
private class DoctorScheduleSyncTest {
    @isTest 
    static void testUpsert() {
        Test.setMock(HttpCalloutMock.class, new DoctorScheduleHttpMock());
        Test.startTest();
        DoctorScheduleSync sync = new DoctorScheduleSync();
        System.enqueueJob(sync);
        Test.stopTest();

        List<Person__c> doctors = [
            SELECT DoctorId__c, Schedule__c, Personal_ID_Number__c, Name, Last_Name__c, First_Name__c, RecordTypeId
            FROM Person__c
        ];
        System.assertEquals(1, doctors.size());
        System.assertEquals([SELECT Id FROM RecordType WHERE SObjectType = 'Person__c' AND Name = 'Doctor'].Id, doctors[0].RecordTypeId);
        System.assertEquals('Grzegorz', doctors[0].First_Name__c);
        System.assertEquals('Król', doctors[0].Last_Name__c);
        System.assertEquals('Dr Grzegorz Król', doctors[0].Name);
        System.assertEquals('61072632139', doctors[0].Personal_ID_Number__c);
        System.assertEquals('Poniedziałek: "9:00 - 14:00"\nWtorek: "10:00 - 14:00"\nŚroda: "9:00 - 14:00"\nCzwartek: "Nie pracuje"\nPiątek: "Nie pracuje"\nSobota: "10:00 - 17:00"\nNiedziela: "8:00 - 13:00"', doctors[0].Schedule__c);
        System.assertEquals('D0000013', doctors[0].DoctorId__c);
    }
}